# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79c2d8bcb61f95e522f105ec0a38c16066a8b0f8ce2d5637d8486935ad8065365335d097148f5957a0ec1f1e4ce32d539d39fe21131f4b0e29cfbd0c2de77783

test:
  secret_key_base: 5173553763b7b7fe99e6196615213061bbba6c8d38df4123369d521655c700707a25f5cc036018cba7b3e1d4b022ea24e7115f03d6fed6e1c82c6b341655271d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
